services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - api
    ports:
      - "3100:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Data Source=SQL1002.site4now.net;Initial Catalog=db_acaeb4_datn;User Id=db_acaeb4_datn_admin;Password=Admin@123;Encrypt=True;TrustServerCertificate=True;"
      JWT__Issuer: UniversityPortal
      JWT__Audience: UniversityPortal
      JWT__ExpiryMinutes: "60"
      JWT__RefreshTokenExpiryDays: "7"
      JWT__Secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data:
