// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityPortal.Infrastructure.Persistence;

#nullable disable

namespace UniversityPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707135035_AddNoiDungTinh")]
    partial class AddNoiDungTinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityPortal.Domain.Entities.BienBanSHCN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("dia_diem");

                    b.Property<int>("GvcnId")
                        .HasColumnType("int")
                        .HasColumnName("gvcn_id");

                    b.Property<int>("LopId")
                        .HasColumnType("int")
                        .HasColumnName("lop_id");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("PhanHoiGvcn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phan_hoi_gvcn");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.Property<int>("ThuKyId")
                        .HasColumnType("int")
                        .HasColumnName("thu_ky_id");

                    b.Property<int>("TuanHocId")
                        .HasColumnType("int")
                        .HasColumnName("tuan_hoc_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GvcnId");

                    b.HasIndex("LopId");

                    b.HasIndex("ThuKyId");

                    b.HasIndex("TuanHocId");

                    b.ToTable("bien_ban_shcn", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.BinhLuanThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("NgayBinhLuan")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_binh_luan");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("tai_khoan_id");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int")
                        .HasColumnName("thong_bao_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("binh_luan_thong_bao", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietCTDT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CtdtId")
                        .HasColumnType("int")
                        .HasColumnName("ctdt_id");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky_id");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("mon_hoc_id");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<bool>("TinhDiemTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("tinh_diem_tb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CtdtId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.ToTable("chi_tiet_ctdt", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int")
                        .HasColumnName("bien_ban_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_cong_viec");

                    b.Property<string>("TrangThaiViec")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("trang_thai_viec");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.ToTable("chi_tiet_cong_viec", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietVangSHCN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int")
                        .HasColumnName("bien_ban_id");

                    b.Property<bool>("CoPhep")
                        .HasColumnType("bit")
                        .HasColumnName("co_phep");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ly_do");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("chi_tiet_vang_shcn", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChuongTrinhDT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("KhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("khoa_hoc");

                    b.Property<string>("MaCtdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_ctdt");

                    b.Property<int>("NganhId")
                        .HasColumnType("int")
                        .HasColumnName("nganh_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaCtdt")
                        .IsUnique();

                    b.HasIndex("NganhId");

                    b.ToTable("chuong_trinh_dt", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DanhSachLopHP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<float?>("DiemQt1")
                        .HasColumnType("real")
                        .HasColumnName("diem_qt1");

                    b.Property<float?>("DiemQt2")
                        .HasColumnType("real")
                        .HasColumnName("diem_qt2");

                    b.Property<float?>("DiemThi")
                        .HasColumnType("real")
                        .HasColumnName("diem_thi");

                    b.Property<float?>("DiemTongKet")
                        .HasColumnType("real")
                        .HasColumnName("diem_tong_ket");

                    b.Property<string>("LoaiDangKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_dang_ky");

                    b.Property<int>("LopHpId")
                        .HasColumnType("int")
                        .HasColumnName("lop_hp_id");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet_id");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<decimal?>("SoTienPhaiDong")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_phai_dong");

                    b.Property<string>("TrangThaiDongTien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai_dong_tien");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai_duyet");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHpId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("SinhVienId", "LopHpId")
                        .IsUnique();

                    b.ToTable("danh_sach_lop_hp", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DanhSachThiLai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<float?>("DiemThiLai")
                        .HasColumnType("real")
                        .HasColumnName("diem_thi_lai");

                    b.Property<int>("LopHpId")
                        .HasColumnType("int")
                        .HasColumnName("lop_hp_id");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet_id");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<decimal>("SoTienPhaiDong")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_phai_dong");

                    b.Property<string>("TrangThaiDongTien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai_dong_tien");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHpId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("danh_sach_thi_lai", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DatPhongThucHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaHoc")
                        .HasColumnType("int")
                        .HasColumnName("ca_hoc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int")
                        .HasColumnName("giao_vien_id");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do");

                    b.Property<DateOnly>("NgayDat")
                        .HasColumnType("date")
                        .HasColumnName("ngay_dat");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet_id");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phong_hoc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("dat_phong_thuc_hanh", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DiemRenLuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DiemTong")
                        .HasColumnType("int")
                        .HasColumnName("diem_tong");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky_id");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("XepLoai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("xep_loai");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("SinhVienId", "HocKyId")
                        .IsUnique();

                    b.ToTable("diem_ren_luyen", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DienDanGiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int")
                        .HasColumnName("giao_vien_id");

                    b.Property<int>("LopId")
                        .HasColumnType("int")
                        .HasColumnName("lop_id");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_gui");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopId");

                    b.ToTable("dien_dan_giao_vien", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MaGv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_gv");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("tai_khoan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaGv")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique();

                    b.ToTable("giao_vien", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocBa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CtdtId")
                        .HasColumnType("int")
                        .HasColumnName("ctdt_id");

                    b.Property<float>("DiemTbcTichLuy")
                        .HasColumnType("real")
                        .HasColumnName("diem_tbc_tich_luy");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int>("SoTinChiTichLuy")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi_tich_luy");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CtdtId");

                    b.HasIndex("SinhVienId", "CtdtId")
                        .IsUnique();

                    b.ToTable("hoc_ba", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int")
                        .HasColumnName("nam_hoc_id");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hoc_ky");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NamHocId");

                    b.ToTable("hoc_ky", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky_id");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThaiDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai_dong");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("SinhVienId", "HocKyId")
                        .IsUnique();

                    b.ToTable("hoc_phi", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.KetQuaAnhVanDauVao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<float?>("DiemTa1")
                        .HasColumnType("real")
                        .HasColumnName("diem_ta1");

                    b.Property<float?>("DiemTa2")
                        .HasColumnType("real")
                        .HasColumnName("diem_ta2");

                    b.Property<float?>("DiemTa3")
                        .HasColumnType("real")
                        .HasColumnName("diem_ta3");

                    b.Property<float?>("DiemThi")
                        .HasColumnType("real")
                        .HasColumnName("diem_thi");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("HinhThucXet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hinh_thuc_xet");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SinhVienId")
                        .IsUnique();

                    b.ToTable("ket_qua_anh_van_dau_vao", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.KhaoSatYKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int")
                        .HasColumnName("diem_danh_gia");

                    b.Property<string>("GopY")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gop_y");

                    b.Property<int>("LopHpId")
                        .HasColumnType("int")
                        .HasColumnName("lop_hp_id");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHpId");

                    b.HasIndex("SinhVienId", "LopHpId")
                        .IsUnique();

                    b.ToTable("khao_sat_y_kien", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopHocPhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiTietCtdtId")
                        .HasColumnType("int")
                        .HasColumnName("chi_tiet_ctdt_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int")
                        .HasColumnName("giao_vien_id");

                    b.Property<int>("HocKyId")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky_id");

                    b.Property<bool>("KhoaBangDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("khoa_bang_diem");

                    b.Property<string>("MaLopHp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_lop_hp");

                    b.Property<bool>("TrangThaiKetThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("trang_thai_ket_thuc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietCtdtId");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MaLopHp")
                        .IsUnique();

                    b.ToTable("lop_hoc_phan", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopSinhHoat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuongTrinhDtId")
                        .HasColumnType("int")
                        .HasColumnName("chuong_trinh_dt_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GvcnId")
                        .HasColumnType("int")
                        .HasColumnName("gvcn_id");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_lop");

                    b.Property<int?>("ThuKyId")
                        .HasColumnType("int")
                        .HasColumnName("thu_ky_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhDtId");

                    b.HasIndex("GvcnId");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.HasIndex("ThuKyId");

                    b.ToTable("lop_sinh_hoat", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_mon");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ten_mon");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaMon")
                        .IsUnique();

                    b.ToTable("mon_hoc", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NamHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("TenNamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ten_nam_hoc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("nam_hoc", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NganhHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_nganh");

                    b.Property<int?>("NganhChaId")
                        .HasColumnType("int")
                        .HasColumnName("nganh_cha_id");

                    b.Property<int?>("PhongBanId")
                        .HasColumnType("int")
                        .HasColumnName("phong_ban_id");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ten_nganh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaNganh")
                        .IsUnique();

                    b.HasIndex("NganhChaId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("nganh_hoc", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NoiDungTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khu_vuc");

                    b.Property<string>("MaMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ma_muc");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhuVuc", "ThuTu");

                    b.ToTable("noi_dung_tinh", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_phong_ban");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("phong_ban", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("LopId")
                        .HasColumnType("int")
                        .HasColumnName("lop_id");

                    b.Property<string>("Mssv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mssv");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("tai_khoan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.HasIndex("Mssv")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique();

                    b.ToTable("sinh_vien", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<int?>("PhongBanId")
                        .HasColumnType("int")
                        .HasColumnName("phong_ban_id");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("vai_tro_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhongBanId");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("tai_khoan", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThoiKhoaBieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("LopHpId")
                        .HasColumnType("int")
                        .HasColumnName("lop_hp_id");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phong_hoc");

                    b.Property<int>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.Property<int>("TuanHocId")
                        .HasColumnType("int")
                        .HasColumnName("tuan_hoc_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHpId");

                    b.HasIndex("TuanHocId");

                    b.ToTable("thoi_khoa_bieu", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_thong_bao");

                    b.Property<int?>("LopNhanId")
                        .HasColumnType("int")
                        .HasColumnName("lop_nhan_id");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("muc_do");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_tao_id");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieu_de");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopNhanId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("thong_bao", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThongBaoDaDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_doc");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_doc");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("tai_khoan_id");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int")
                        .HasColumnName("thong_bao_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("ThongBaoId", "TaiKhoanId")
                        .IsUnique();

                    b.ToTable("thong_bao_da_doc", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TuanHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MaTuan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_tuan");

                    b.Property<int>("NamHocId")
                        .HasColumnType("int")
                        .HasColumnName("nam_hoc_id");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int>("SoThuTuTuan")
                        .HasColumnType("int")
                        .HasColumnName("so_thu_tu_tuan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MaTuan")
                        .IsUnique();

                    b.HasIndex("NamHocId");

                    b.ToTable("tuan_hoc", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("vai_tro", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.YeuCauHanhChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FileDinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_dinh_kem");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu_admin");

                    b.Property<string>("LoaiGiayXacNhan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("loai_giay_xac_nhan");

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loai_yeu_cau");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet_id");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("yeu_cau_hanh_chinh", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.YeuCauSuaDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int")
                        .HasColumnName("giao_vien_id");

                    b.Property<int>("LopHpId")
                        .HasColumnType("int")
                        .HasColumnName("lop_hp_id");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet_id");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("LopHpId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("yeu_cau_sua_diem", (string)null);
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.BienBanSHCN", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "Gvcn")
                        .WithMany("BienBanSHCNs")
                        .HasForeignKey("GvcnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.LopSinhHoat", "Lop")
                        .WithMany("BienBanSHCNs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "ThuKy")
                        .WithMany("BienBanSHCNThuKy")
                        .HasForeignKey("ThuKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TuanHoc", "TuanHoc")
                        .WithMany("BienBanSHCNs")
                        .HasForeignKey("TuanHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gvcn");

                    b.Navigation("Lop");

                    b.Navigation("ThuKy");

                    b.Navigation("TuanHoc");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.BinhLuanThongBao", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.ThongBao", "ThongBao")
                        .WithMany("BinhLuans")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietCTDT", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.ChuongTrinhDT", "ChuongTrinhDT")
                        .WithMany("ChiTietCTDTs")
                        .HasForeignKey("CtdtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.HocKy", "HocKy")
                        .WithMany("ChiTietCTDTs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("ChiTietCTDTs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDT");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietCongViec", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.BienBanSHCN", "BienBan")
                        .WithMany("ChiTietCongViecs")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietVangSHCN", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.BienBanSHCN", "BienBan")
                        .WithMany("ChiTietVangSHCNs")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("ChiTietVangSHCNs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChuongTrinhDT", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.NganhHoc", "Nganh")
                        .WithMany("ChuongTrinhDTs")
                        .HasForeignKey("NganhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DanhSachLopHP", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachLopHPs")
                        .HasForeignKey("LopHpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("DanhSachLopHPs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDuyet");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DanhSachThiLai", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachThiLais")
                        .HasForeignKey("LopHpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("DanhSachThiLais")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDuyet");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DatPhongThucHanh", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "GiaoVien")
                        .WithMany("DatPhongThucHanhs")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GiaoVien");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DiemRenLuyen", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.HocKy", "HocKy")
                        .WithMany("DiemRenLuyens")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("DiemRenLuyens")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.DienDanGiaoVien", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "GiaoVien")
                        .WithMany("DienDanGiaoViens")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.LopSinhHoat", "Lop")
                        .WithMany("DienDanGiaoViens")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.GiaoVien", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("GiaoVien")
                        .HasForeignKey("UniversityPortal.Domain.Entities.GiaoVien", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocBa", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.ChuongTrinhDT", "ChuongTrinhDT")
                        .WithMany("HocBas")
                        .HasForeignKey("CtdtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("HocBas")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDT");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocKy", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany("HocKys")
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocPhi", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.HocKy", "HocKy")
                        .WithMany("HocPhis")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("HocPhis")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.KetQuaAnhVanDauVao", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithOne("KetQuaAnhVanDauVao")
                        .HasForeignKey("UniversityPortal.Domain.Entities.KetQuaAnhVanDauVao", "SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.KhaoSatYKien", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("KhaoSatYKiens")
                        .HasForeignKey("LopHpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("KhaoSatYKiens")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopHocPhan", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.ChiTietCTDT", "ChiTietCTDT")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("ChiTietCtdtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "GiaoVien")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.HocKy", "HocKy")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietCTDT");

                    b.Navigation("GiaoVien");

                    b.Navigation("HocKy");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopSinhHoat", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.ChuongTrinhDT", "ChuongTrinhDT")
                        .WithMany("LopSinhHoats")
                        .HasForeignKey("ChuongTrinhDtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "Gvcn")
                        .WithMany("LopSinhHoatGVCN")
                        .HasForeignKey("GvcnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "ThuKy")
                        .WithMany("LopSinhHoatThuKy")
                        .HasForeignKey("ThuKyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuongTrinhDT");

                    b.Navigation("Gvcn");

                    b.Navigation("ThuKy");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NganhHoc", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.NganhHoc", "NganhCha")
                        .WithMany("NganhCons")
                        .HasForeignKey("NganhChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityPortal.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("NganhHocs")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NganhCha");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.SinhVien", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopSinhHoat", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("UniversityPortal.Domain.Entities.SinhVien", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityPortal.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThoiKhoaBieu", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("ThoiKhoaBieus")
                        .HasForeignKey("LopHpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TuanHoc", "TuanHoc")
                        .WithMany("ThoiKhoaBieus")
                        .HasForeignKey("TuanHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("TuanHoc");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.LopSinhHoat", "LopNhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("LopNhanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopNhan");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThongBaoDaDoc", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.ThongBao", "ThongBao")
                        .WithMany("ThongBaoDaDocs")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TuanHoc", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.NamHoc", "NamHoc")
                        .WithMany("TuanHocs")
                        .HasForeignKey("NamHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.YeuCauHanhChinh", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UniversityPortal.Domain.Entities.SinhVien", "SinhVien")
                        .WithMany("YeuCauHanhChinhs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.YeuCauSuaDiem", b =>
                {
                    b.HasOne("UniversityPortal.Domain.Entities.GiaoVien", "GiaoVien")
                        .WithMany("YeuCauSuaDiems")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("YeuCauSuaDiems")
                        .HasForeignKey("LopHpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityPortal.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHocPhan");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.BienBanSHCN", b =>
                {
                    b.Navigation("ChiTietCongViecs");

                    b.Navigation("ChiTietVangSHCNs");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChiTietCTDT", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ChuongTrinhDT", b =>
                {
                    b.Navigation("ChiTietCTDTs");

                    b.Navigation("HocBas");

                    b.Navigation("LopSinhHoats");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.GiaoVien", b =>
                {
                    b.Navigation("BienBanSHCNs");

                    b.Navigation("DatPhongThucHanhs");

                    b.Navigation("DienDanGiaoViens");

                    b.Navigation("LopHocPhans");

                    b.Navigation("LopSinhHoatGVCN");

                    b.Navigation("YeuCauSuaDiems");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.HocKy", b =>
                {
                    b.Navigation("ChiTietCTDTs");

                    b.Navigation("DiemRenLuyens");

                    b.Navigation("HocPhis");

                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopHocPhan", b =>
                {
                    b.Navigation("DanhSachLopHPs");

                    b.Navigation("DanhSachThiLais");

                    b.Navigation("KhaoSatYKiens");

                    b.Navigation("ThoiKhoaBieus");

                    b.Navigation("YeuCauSuaDiems");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.LopSinhHoat", b =>
                {
                    b.Navigation("BienBanSHCNs");

                    b.Navigation("DienDanGiaoViens");

                    b.Navigation("SinhViens");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.MonHoc", b =>
                {
                    b.Navigation("ChiTietCTDTs");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NamHoc", b =>
                {
                    b.Navigation("HocKys");

                    b.Navigation("TuanHocs");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.NganhHoc", b =>
                {
                    b.Navigation("ChuongTrinhDTs");

                    b.Navigation("NganhCons");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.PhongBan", b =>
                {
                    b.Navigation("NganhHocs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.SinhVien", b =>
                {
                    b.Navigation("BienBanSHCNThuKy");

                    b.Navigation("ChiTietVangSHCNs");

                    b.Navigation("DanhSachLopHPs");

                    b.Navigation("DanhSachThiLais");

                    b.Navigation("DiemRenLuyens");

                    b.Navigation("HocBas");

                    b.Navigation("HocPhis");

                    b.Navigation("KetQuaAnhVanDauVao");

                    b.Navigation("KhaoSatYKiens");

                    b.Navigation("LopSinhHoatThuKy");

                    b.Navigation("YeuCauHanhChinhs");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("GiaoVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.ThongBao", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("ThongBaoDaDocs");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.TuanHoc", b =>
                {
                    b.Navigation("BienBanSHCNs");

                    b.Navigation("ThoiKhoaBieus");
                });

            modelBuilder.Entity("UniversityPortal.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
